name: Recoleccion Diario de Cotizaciones

on:
  schedule:
    - cron: '0 21 * * 1-5'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  recolectar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar librerías
        run: |
          pip install requests

      - name: Ejecutar script de recoleccion
        run: |
          python coleccionista.py

        - name: Guardar y subir cambios
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git status
          git add -f precios.json historial.json
          git commit -m "Actualizar cotizaciones [skip ci]" || echo "Sin cambios nuevos"
          git push origin HEAD:${{ github.ref_name }}


      
